name: 'Publish to dev.to'
description: 'Publish markdown files as articles to dev.to platform, using assets hosted on GitHub.'
author: 'sinedied'
branding:
  icon: 'upload'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'Dockerfile'
  main: 'dist/index.js'
inputs:
  devto_key:
    description: 'Your dev.to personal API key to publish and update articles'
    required: true
  github_token:
    description: 'Your GitHub access token to update files with ID once published'
    required: true
  files:
    description: 'One or more glob patterns of files to include'
    required: false
    default: 'posts/**/*.md'
  branch:
    description: 'The git branch to use'
    required: false
    default: 'main'
  conventional_commits:
    description: 'Use conventional commits messages'
    required: false
    default: false
